name: demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Environment
  flutter_dotenv: ^6.0.0

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.2
  firebase_messaging: ^16.3.0

  # Google Sign In
  google_sign_in: ^6.2.2

  # Networking
  http: ^1.5.0

  # Charts
  fl_chart: ^1.1.1

  # Localization
  intl: ^0.20.2

  # File/Image Pickers
  file_picker: ^10.3.2
  image_picker: ^1.2.0

  # AI
  googleai_dart: ^3.0.0
  # google_generative_ai: ^0.4.7
  # Recommended to remove if using googleai_dart

  # PDF
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_pdf: ^32.1.23

  # Backend
  supabase_flutter: ^2.12.0

  # Utilities
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  file_saver: ^0.3.1

  # Audio
  flutter_sound: ^9.28.0
  audioplayers: ^6.5.1

  # Calendar
  table_calendar: ^3.2.0

  # UI
  flutter_floating_bottom_bar: ^1.4.0
  google_fonts: ^6.3.1
  flex_color_scheme: ^8.3.0
  animations: ^2.0.11
  lottie: ^3.3.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animation/
    - assets/icons/
    - assets/images/
    - assets/templates/